theme: jekyll-theme-minimal
title: Blockchain-Powered-Procurement-System
author: Abhishek Vispute
email: abhivispute33@gmail.com
google-site-verification: "35znUrvR4YExdysvKnRDNYHQEOvqNC69kUF20QqVsR8"


