theme: jekyll-theme-minimal
title: Blockchain-Powered-Procurement-System
author: Abhishek Vispute
email: abhivispute33@gmail.com
keywords: "supply chain management, Procurement, Tenders, blockchain, gail, abhishek vispute"
  
gems:
- jekyll-paginate
- jekyll-gist


